/*
This file was generated by https://github.com/pmndrs/gltfjsx and then
customized manually. It uses drei's new useAnimations hook which extracts
all actions and sets up a THREE.AnimationMixer for it so that you don't have to.
All of the assets actions, action-names and clips are available in its output. 
*/

import { useEffect, useMemo, useState } from 'react'
import { SkeletonUtils } from 'three-stdlib'
import { useGraph } from '@react-three/fiber'
import { useAnimations, useCursor, useGLTF, useTexture } from '@react-three/drei'
import { a, useSpring } from '@react-spring/three'

import model from '../../models/stacy.glb'
import texturePath from '../../textures/stacy.jpg'

const Model = ({ pose, ...props}: any) => {
  // Fetch model and a separate texture
  const { scene, animations } = useGLTF(model) as any
  const texture = useTexture(texturePath)

  // Skinned meshes cannot be re-used in threejs without cloning them
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  // useGraph creates two flat object collections for nodes and materials
  const { nodes } = useGraph(clone) as any

  // Extract animation actions
  const { ref, actions, names } = useAnimations(animations)

  // Hover and animation-index states
  const [hovered, setHovered] = useState(false)
  const [index, setIndex] = useState(pose)

  // Animate the selection halo
  const { color, scale } = useSpring({ 
    scale: hovered ? [1.15, 1.15, 1] : [1, 1, 1], 
    color: hovered ? 'hotpink' : 'aquamarine' 
  }) as any

  // Change cursor on hover-state
  useCursor(hovered)

  // Change animation when the index changes
  useEffect(() => {
    // Reset and fade in animation after an index has been changed
    actions[names[index]]?.reset().fadeIn(0.5).play()
    // In the clean-up phase, fade it out
    return () => actions[names[index]]?.fadeOut(0.5) as any
  }, [index, actions, names])

  return (
    <group ref={ref} {...props} dispose={null} >
      <group 
        onPointerOver={() => setHovered(true)}
        onPointerOut={() => setHovered(false)}
        onClick={() => setIndex((index + 1) % names.length)}
        rotation-x={Math.PI / 2} 
        scale={0.01}>
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
          castShadow
          receiveShadow
          geometry={nodes.stacy.geometry}
          skeleton={nodes.stacy.skeleton}
          rotation-x={-Math.PI / 2}
          scale={100}>
          <meshStandardMaterial map={texture} map-flipY={false} /> 
        </skinnedMesh>
      </group>
      <a.mesh receiveShadow position={[0, 1, -1]} scale={scale}>
        <circleBufferGeometry args={[0.6, 64]} />
        {/* @ts-ignore */}
        <a.meshStandardMaterial color={color} />
      </a.mesh>
    </group>
  )
}

export default Model