/// <reference types='react-scripts' />
declare module 'lodash-es/without'
declare module 'babel-plugin-glsl/macro'
declare module 'random-words'
declare module '*.svg'
declare module '*.mp4'
declare module '*.glb'
declare module '*.gltf'
declare module '*.CUBE'
declare module '*.hdr'
declare module '*.woff'
declare module '*.ttf'